### ISSUE TITLE
Build Issue:  getRandomIonsInBox()

### ISSUE THREAD

**Issue by MichaelSenko** [IPAMS/IDSimF#1]
I'm following the build instructions and get the following error.  The suggestion of using GetRandomPositionsInBox() is not right because its return type is not correct.  I see this call used in many places in test_tree.cpp and a couple of the applications, so clearly this is not a typo.

[ 41%] Building CXX object tests/modules/BTree/CMakeFiles/test_BTree.dir/test_node.cpp.o
/home/mike/IDSimF/tests/modules/BTree/test_node.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____15()’:
/home/mike/IDSimF/tests/modules/BTree/test_node.cpp:453:87: error: ‘getRandomIonsInBox’ is not a member of ‘ParticleSimulation::util’; did you mean ‘getRandomPositionsInBox’?
  453 |         std::vector<std::unique_ptr<BTree::Particle>> ions= ParticleSimulation::util::getRandomIonsInBox(nions,2.0,corner,boxSize);
      |                                                                                       ^~~~~~~~~~~~~~~~~~
      |                                                                                       getRandomPositionsInBox
make[2]: *** [tests/modules/BTree/CMakeFiles/test_BTree.dir/build.make:89: tests/modules/BTree/CMakeFiles/test_BTree.dir/test_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:959: tests/modules/BTree/CMakeFiles/test_BTree.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by wwissdorf** [comment]
Indeed, GetRandomPositionsInBox() was removed recently and a generic particle start zone class was introduced. The change was pushed to master too early. I have temporarily reverted the removal of GetRandomPositionsInBox(). All targets should build now.
