### ISSUE TITLE
ctest failures with current build

### ISSUE THREAD

**Issue by MichaelSenko** [IPAMS/IDSimF#2]
With a fresh build, running ctest fails 13 of 33 tests.
The following tests FAILED:
          6 - test_simulations (Failed)
          8 - BT-spaceChargeMinimalSim_benchmarkRunShort (Child aborted)
         10 - BT-spaceChargeSimpleSim_benchmarkRunShort (Child aborted)
         11 - BT-staticSimionPASim_benchmarkRunShort (Child aborted)
         17 - BT-RS-IMSSim_waterCluster_HS (Child aborted)
         18 - BT-RS-IMSSim_waterCluster_SDS (Child aborted)
         19 - BT-RS-IMSSim_no_reaction (Child aborted)
         20 - BT-RS-IMSSim_waterCluster_no_transport (Child aborted)
         21 - BT-RS-IMSSim_waterCluster_simple (Child aborted)
         22 - BT-RS-IMSSim_waterCluster_thermalizing (Child aborted)
         25 - BT-QITSim_fixedRF_ionCloud (Child aborted)
         28 - BT-generalTrapSim_simpleCapacitor (Child aborted)
         30 - BT-generalTrapSim_simpleCapacitor_serial (Child aborted)

**Comment by wwissdorf** [comment]
I cannot reproduce this. I pass all tests with the master branch on two MacOS and a Linux system with different compiler toolchains. 
Can you pull the latest commit from master branch and discard your build directory / cmake configuration entirely for a new build from scratch?

**Comment by MichaelSenko** [comment]
Full rebuild has eliminated the test failures  Must have been something funny with the build after I did a pull earlier today.

Thanks
Mike
